"""Simulated operator (human) node for the SafeCollab kitting cell.

Architecture note (AGENTS.md §3, §6 FR-11)
-------------------------------------------
``human_node`` drives the *ground-truth* operator model.  It:

* generates **randomisable** operator paths that include tray-reach waypoints
  (FR-11 / AT-6);
* broadcasts the ground-truth TF ``world → human_gt`` for simulation
  diagnostics;
* publishes **no safety output** — the safety monitor consumes the *perceived*
  ``world → human`` TF broadcast by ``perception_node`` (Stream C), not the
  ground truth.

Module layout
-------------
Pure-Python classes (``Waypoint``, ``OperatorPath``, ``OperatorModel``) are at
the top with **no ROS imports** — unit-testable without a live ROS graph.

The ROS 2 node wrapper lives inside ``main()`` (``# pragma: no cover``) so that
importing this module in a plain-Python test environment never fails due to a
missing ``rclpy`` installation.

Cell geometry (world frame, metres) — from ``urdf/cell.xacro``
---------------------------------------------------------------
* ``table_top`` : (0, 0, 0.74)
* ``kitting_tray`` centre: table_top + (0.35, 0, 0.02) → world (0.35, 0, 0.76)
* Tray footprint: x ∈ [0.20, 0.50], y ∈ [-0.20, +0.20], top surface z ≈ 0.78
* Operator stands at the front (+x) long side of the table.
"""

from __future__ import annotations

import math
import random
from dataclasses import dataclass
from typing import List, Optional, Sequence, Tuple

# ---------------------------------------------------------------------------
# Cell geometry constants (from cell.xacro)
# ---------------------------------------------------------------------------

#: World-frame centre of the kitting tray (x, y, z).
TRAY_CENTRE: tuple[float, float, float] = (0.35, 0.0, 0.76)

#: Half-extents of the tray footprint (x and y).
TRAY_HALF_X: float = 0.15
TRAY_HALF_Y: float = 0.20

#: Top surface of the tray (z).
TRAY_TOP_Z: float = TRAY_CENTRE[2] + 0.02  # 0.78 m

#: Hand height of the operator when performing a tray reach.
REACH_Z: float = 0.82

#: Typical hand heights for standing / leaning poses.
STANDING_Z: float = 1.10
APPROACH_Z: float = 0.95


# ---------------------------------------------------------------------------
# Data types
# ---------------------------------------------------------------------------


@dataclass
class Waypoint:
    """A 3-D world-frame position with an arrival time.

    Attributes:
        x: World-frame x coordinate (metres).
        y: World-frame y coordinate (metres).
        z: World-frame z coordinate (metres).
        t: Time to reach this waypoint from the path start (seconds).
    """

    x: float
    y: float
    z: float
    t: float

    @property
    def position(self) -> Tuple[float, float, float]:
        """(x, y, z) position tuple."""
        return (self.x, self.y, self.z)


def _lerp(a: float, b: float, alpha: float) -> float:
    """Linear interpolation between ``a`` and ``b`` by factor ``alpha``."""
    return a + alpha * (b - a)


def _interpolate_waypoints(
    waypoints: Sequence[Waypoint],
    t: float,
) -> Tuple[float, float, float]:
    """Linearly interpolate between consecutive waypoints at time ``t``.

    If ``t`` is before the first waypoint, the first position is returned.
    If ``t`` is after the last waypoint, the last position is returned.

    Args:
        waypoints: Ordered sequence of ``Waypoint`` objects.
        t: Query time in seconds.

    Returns:
        ``(x, y, z)`` world-frame position.
    """
    if not waypoints:
        return (0.0, 0.0, 0.0)

    t = max(0.0, t)

    # Walk segment-by-segment
    for i in range(len(waypoints) - 1):
        w0 = waypoints[i]
        w1 = waypoints[i + 1]
        if t <= w1.t:
            dt = w1.t - w0.t
            alpha = (t - w0.t) / dt if dt > 1e-12 else 0.0
            alpha = max(0.0, min(1.0, alpha))
            return (
                _lerp(w0.x, w1.x, alpha),
                _lerp(w0.y, w1.y, alpha),
                _lerp(w0.z, w1.z, alpha),
            )

    # Past the last waypoint
    last = waypoints[-1]
    return last.position


# ---------------------------------------------------------------------------
# Operator path
# ---------------------------------------------------------------------------


class OperatorPath:
    """A timed waypoint sequence for one operator traversal.

    The path **must** include at least one waypoint inside the kitting-tray
    horizontal footprint (a "tray reach") to satisfy FR-11.

    The path is generated by :meth:`generate_random`, which randomises:

    * which side of the table (+y or −y) the operator approaches from;
    * the exact tray-reach position within the tray footprint;
    * approach timing (±40 % speed variation).
    """

    def __init__(self, waypoints: List[Waypoint]) -> None:
        """Initialise with an ordered list of waypoints.

        Raises:
            ValueError: If ``waypoints`` is empty.
        """
        if not waypoints:
            raise ValueError("OperatorPath requires at least one waypoint")
        self._waypoints: List[Waypoint] = list(waypoints)

    @property
    def waypoints(self) -> List[Waypoint]:
        """Ordered list of waypoints (defensive copy)."""
        return list(self._waypoints)

    @property
    def duration_s(self) -> float:
        """Total duration of the path (arrival time of the last waypoint)."""
        return self._waypoints[-1].t

    def has_tray_reach(self) -> bool:
        """Return ``True`` if any waypoint lies within the tray footprint.

        "Within the tray footprint" means the x and y coordinates are within
        the tray's horizontal bounds (ignoring z so that above-tray and
        inside-tray positions both count).
        """
        cx, cy, _ = TRAY_CENTRE
        return any(
            abs(wp.x - cx) <= TRAY_HALF_X and abs(wp.y - cy) <= TRAY_HALF_Y
            for wp in self._waypoints
        )

    def tray_reach_waypoints(self) -> List[Waypoint]:
        """Return waypoints that lie inside the tray footprint."""
        cx, cy, _ = TRAY_CENTRE
        return [
            wp
            for wp in self._waypoints
            if abs(wp.x - cx) <= TRAY_HALF_X and abs(wp.y - cy) <= TRAY_HALF_Y
        ]

    @classmethod
    def generate_random(cls, rng: Optional[random.Random] = None) -> "OperatorPath":
        """Generate a random operator path that includes a tray reach.

        Randomises approach side, reach position within the tray footprint, and
        approach speed, satisfying FR-11 (AT-6 randomised operator paths).

        Args:
            rng: Optional seeded ``random.Random`` instance for reproducibility.
                 If ``None``, a fresh (unseeded) instance is used.

        Returns:
            A new ``OperatorPath`` whose :meth:`has_tray_reach` is ``True``.
        """
        if rng is None:
            rng = random.Random()

        # Operator approaches from the +y or −y side of the table
        side_y = rng.choice([0.65, -0.65])

        # Randomise the tray-reach position within the tray footprint
        reach_x = TRAY_CENTRE[0] + rng.uniform(-TRAY_HALF_X * 0.8, TRAY_HALF_X * 0.8)
        reach_y = rng.uniform(-TRAY_HALF_Y * 0.6, TRAY_HALF_Y * 0.6)

        # Timing scale (±40 % speed variation)
        t_scale = rng.uniform(0.7, 1.4)

        waypoints = [
            # 0 — standing back from table
            Waypoint(x=0.9, y=side_y, z=STANDING_Z, t=0.0),
            # 1 — table edge, leaning toward tray area
            Waypoint(x=0.7, y=side_y * 0.4, z=APPROACH_Z, t=round(2.0 * t_scale, 3)),
            # 2 — hover above tray
            Waypoint(x=reach_x, y=reach_y, z=APPROACH_Z, t=round(4.0 * t_scale, 3)),
            # 3 — tray reach (hand inside tray)
            Waypoint(x=reach_x, y=reach_y, z=REACH_Z, t=round(5.5 * t_scale, 3)),
            # 4 — withdraw (hand back above tray)
            Waypoint(x=reach_x, y=reach_y, z=APPROACH_Z, t=round(7.0 * t_scale, 3)),
            # 5 — step back from table
            Waypoint(x=0.7, y=side_y * 0.4, z=APPROACH_Z, t=round(9.0 * t_scale, 3)),
            # 6 — return to standing
            Waypoint(x=0.9, y=side_y, z=STANDING_Z, t=round(11.0 * t_scale, 3)),
        ]

        return cls(waypoints)


# ---------------------------------------------------------------------------
# Operator model
# ---------------------------------------------------------------------------


class OperatorModel:
    """Simulated operator model: advances along an ``OperatorPath``.

    ``position_at(t)`` returns the world-frame ``(x, y, z)`` hand position at
    time ``t`` by linearly interpolating between consecutive waypoints.  When
    the path ends, :meth:`is_complete` returns ``True``; the caller (HumanNode)
    is responsible for generating and switching to a fresh path.

    This class contains no ROS imports and is fully unit-testable.
    """

    def __init__(self, path: OperatorPath) -> None:
        self._path = path

    @property
    def path(self) -> OperatorPath:
        """The current operator path."""
        return self._path

    @path.setter
    def path(self, new_path: OperatorPath) -> None:
        """Replace the current path (e.g., when a cycle ends)."""
        self._path = new_path

    def position_at(self, t: float) -> Tuple[float, float, float]:
        """World-frame ``(x, y, z)`` hand position at time ``t``.

        Clamps ``t`` to ``[0, duration_s]`` — does not loop; call
        :meth:`is_complete` to detect end-of-path.
        """
        return _interpolate_waypoints(self._path.waypoints, t)

    def is_complete(self, t: float) -> bool:
        """Return ``True`` when the path has ended at time ``t``."""
        return t >= self._path.duration_s

    @staticmethod
    def distance_to_point(
        pos: Tuple[float, float, float],
        target: Tuple[float, float, float],
    ) -> float:
        """Euclidean distance between two 3-D world-frame points."""
        return math.sqrt(sum((a - b) ** 2 for a, b in zip(pos, target)))


# ---------------------------------------------------------------------------
# ROS 2 node wrapper  (requires rclpy — excluded from unit-test coverage)
# ---------------------------------------------------------------------------


def main(args=None):  # pragma: no cover
    """Entry point for the ``human_node`` ROS 2 executable.

    All ROS imports are deferred to here so that importing this module in a
    plain-Python test environment (no ROS) does not raise ``ImportError``.

    The node broadcasts the **ground-truth** TF ``world → human_gt`` at 50 Hz.
    The frame is named ``human_gt`` (not ``human``) to distinguish it from the
    *perceived* ``world → human`` TF published by ``perception_node``; the safety
    monitor consumes only the perceived TF.
    """
    import rclpy
    from geometry_msgs.msg import TransformStamped
    from rclpy.node import Node
    from tf2_ros import TransformBroadcaster

    class HumanNode(Node):
        """ROS 2 wrapper around ``OperatorModel``.

        Generates a random ``OperatorPath`` at start-up, then replaces it with a
        fresh random path each time the current path completes.  Broadcasts the
        ground-truth ``world → human_gt`` TF at 50 Hz.
        """

        _GT_FRAME = "human_gt"
        _WORLD_FRAME = "world"
        _TIMER_HZ = 50.0

        def __init__(self) -> None:
            super().__init__("human_node")
            self._rng = random.Random()
            path = OperatorPath.generate_random(self._rng)
            self._model = OperatorModel(path)
            self._br = TransformBroadcaster(self)
            self._start_time: Optional[float] = None
            self._timer = self.create_timer(1.0 / self._TIMER_HZ, self._tick)
            self.get_logger().info(
                "[human_node] started; broadcasting world -> human_gt at "
                f"{self._TIMER_HZ:.0f} Hz"
            )

        def _tick(self) -> None:
            """Timer callback: advance the operator and broadcast the TF."""
            now = self.get_clock().now()
            now_s = now.nanoseconds * 1e-9

            if self._start_time is None:
                self._start_time = now_s

            t = now_s - self._start_time

            # Regenerate path when current one is complete
            if self._model.is_complete(t):
                new_path = OperatorPath.generate_random(self._rng)
                self._model.path = new_path
                self._start_time = now_s
                t = 0.0
                self.get_logger().debug("[human_node] new operator path generated")

            x, y, z = self._model.position_at(t)

            tf_msg = TransformStamped()
            tf_msg.header.stamp = now.to_msg()
            tf_msg.header.frame_id = self._WORLD_FRAME
            tf_msg.child_frame_id = self._GT_FRAME
            tf_msg.transform.translation.x = x
            tf_msg.transform.translation.y = y
            tf_msg.transform.translation.z = z
            tf_msg.transform.rotation.w = 1.0  # no rotation for the hand point
            self._br.sendTransform(tf_msg)

    rclpy.init(args=args)
    node = HumanNode()
    try:
        rclpy.spin(node)
    except KeyboardInterrupt:
        pass
    finally:
        node.destroy_node()
        # On SIGINT, rclpy's default signal handler already shuts the context
        # down; calling rclpy.shutdown() again raises RCLError. Guard with ok().
        if rclpy.ok():
            rclpy.shutdown()


if __name__ == "__main__":  # pragma: no cover
    main()
